BikeSharing/config/routes.rb
Rails.application.routes.draw do
  get 'bookmark_station/unbookmark'

  get 'bookmark_station/bookmark'

  get 'bookmark_station/list'

  get 'bookmark_station/list_rank'

  resources :station_histories
  resources :open_times
  resources :positions
  get 'stations/free_slots/:sort', to: 'stations#free_slots', :as => :free_slots1
  get 'stations/free_slots/', to: 'stations#free_slots', :as => :free_slots
  resources :stations
  get 'api/index'
  get 'api/free_slots_bikes'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root_url
  root 'api#index'

end

BikeSharing/app/models/station_history.rb
class StationHistory < ApplicationRecord
  belongs_to :station
end

BikeSharing/app/controllers/station_histories_controller.rb
class StationHistoriesController < ApplicationController
  before_action :set_station_history, only: [:show, :edit, :update, :destroy]

  # GET /station_histories
  # GET /station_histories.json
  def index
    @station_histories = StationHistory.all
  end

  # GET /station_histories/1
  # GET /station_histories/1.json
  def show
  end

  # GET /station_histories/new
  def new
    @station_history = StationHistory.new
  end

  # GET /station_histories/1/edit
  def edit
  end

  # POST /station_histories
  # POST /station_histories.json
  def create
    @station_history = StationHistory.new(station_history_params)

    respond_to do |format|
      if @station_history.save
        format.html { redirect_to @station_history, notice: 'Station history was successfully created.' }
        format.json { render :show, status: :created, location: @station_history }
      else
        format.html { render :new }
        format.json { render json: @station_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /station_histories/1
  # PATCH/PUT /station_histories/1.json
  def update
    respond_to do |format|
      if @station_history.update(station_history_params)
        format.html { redirect_to @station_history, notice: 'Station history was successfully updated.' }
        format.json { render :show, status: :ok, location: @station_history }
      else
        format.html { render :edit }
        format.json { render json: @station_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /station_histories/1
  # DELETE /station_histories/1.json
  def destroy
    @station_history.destroy
    respond_to do |format|
      format.html { redirect_to station_histories_url, notice: 'Station history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station_history
      @station_history = StationHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_history_params
      params.require(:station_history).permit(:free_slots, :free_bikes, :rate)
    end
end

BikeSharing/app/helpers/station_histories_helper.rb
module StationHistoriesHelper
end

BikeSharing/app/views/station_histories/_form.html.erb
<%= form_with(model: station_history, local: true) do |form| %>
  <% if station_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station_history.errors.count, "error") %> prohibited this station_history from being saved:</h2>

      <ul>
      <% station_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :free_slots %>
    <%= form.number_field :free_slots, id: :station_history_free_slots %>
  </div>

  <div class="field">
    <%= form.label :free_bikes %>
    <%= form.number_field :free_bikes, id: :station_history_free_bikes %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate, id: :station_history_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BikeSharing/app/views/station_histories/edit.html.erb
<h1>Editing Station History</h1>

<%= render 'form', station_history: @station_history %>

<%= link_to 'Show', @station_history %> |
<%= link_to 'Back', station_histories_path %>

BikeSharing/app/views/station_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Station Histories</h1>

<table>
  <thead>
    <tr>
      <th>Free slots</th>
      <th>Free bikes</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @station_histories.each do |station_history| %>
      <tr>
        <td><%= station_history.free_slots %></td>
        <td><%= station_history.free_bikes %></td>
        <td><%= station_history.rate %></td>
        <td><%= link_to 'Show', station_history %></td>
        <td><%= link_to 'Edit', edit_station_history_path(station_history) %></td>
        <td><%= link_to 'Destroy', station_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station History', new_station_history_path %>

BikeSharing/app/views/station_histories/new.html.erb
<h1>New Station History</h1>

<%= render 'form', station_history: @station_history %>

<%= link_to 'Back', station_histories_path %>

BikeSharing/app/views/station_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Free slots:</strong>
  <%= @station_history.free_slots %>
</p>

<p>
  <strong>Free bikes:</strong>
  <%= @station_history.free_bikes %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @station_history.rate %>
</p>

<%= link_to 'Edit', edit_station_history_path(@station_history) %> |
<%= link_to 'Back', station_histories_path %>