BikeSharing/config/routes.rb
Rails.application.routes.draw do
  get 'bookmark_station/unbookmark'

  get 'bookmark_station/bookmark'

  get 'bookmark_station/list'

  get 'bookmark_station/list_rank'

  resources :station_histories
  resources :open_times
  resources :positions
  get 'stations/free_slots/:sort', to: 'stations#free_slots', :as => :free_slots1
  get 'stations/free_slots/', to: 'stations#free_slots', :as => :free_slots
  resources :stations
  get 'api/index'
  get 'api/free_slots_bikes'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root_url
  root 'api#index'

end

BikeSharing/app/models/station.rb
class Station < ApplicationRecord
  has_many :station_histories
  has_many :bookmark_stations
  has_many :users, through: :bookmark_stations
end

BikeSharing/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  def free_slots
    @free_slot = Station.where("empty_slots > 0")

    if params[:sort] == "name"
      @free_slot = @free_slot.order("name asc")
      return
    end

    @free_slot = @free_slot.order("empty_slots desc")

  end
  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:company,
                                      :free_bikes,
                                      :empty_slots,
                                      :slots,
                                      :name,
                                      :latitude,
                                      :longitude,
                                      :citybik_station_uid,
                                      :citybik_station_id)
    end
end

BikeSharing/app/helpers/stations_helper.rb
module StationsHelper
end

BikeSharing/app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :station_company %>
  </div>

  <div class="field">
    <%= form.label :free_bikes %>
    <%= form.number_field :free_bikes, id: :station_free_bikes %>
  </div>

  <div class="field">
    <%= form.label :empty_slots %>
    <%= form.number_field :empty_slots, id: :station_empty_slots %>
  </div>

  <div class="field">
    <%= form.label :slots %>
    <%= form.number_field :slots, id: :station_slots %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :station_name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :station_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :station_longitude %>
  </div>

  <div class="field">
    <%= form.label :citybik_station_uid %>
    <%= form.text_field :citybik_station_uid, id: :station_citybik_station_uid %>
  </div>

  <div class="field">
    <%= form.label :citybik_station_id %>
    <%= form.text_field :citybik_station_id, id: :station_citybik_station_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BikeSharing/app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

BikeSharing/app/views/stations/free_slots.html.erb
<p id="notice"><%= notice %></p>

<div class="container free_slots">
  <h2>Estações com slots livres</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><a href="<%= free_slots1_path('name') %>">Estação</a></th>
        <th><a href="<%= free_slots_path %>">Slots livres</th>
      </tr>
    </thead>
    <tbody>
      <% @free_slot.each do |s| %>
        <tr>
          <td> <%= "#{s.name}" %> </td>
          <td> <%= "#{s.empty_slots}" %> </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

BikeSharing/app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations <%= Station.count %></h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Free bikes</th>
      <th>Empty Slots</th>
      <th>Slots</th>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>citybik_station_uid</th>
      <th>citybik_station_id</th>
      <th colspan="9"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.company %></td>
        <td><%= station.free_bikes %></td>
        <td><%= station.empty_slots %></td>
        <td><%= station.slots %></td>
        <td><%= station.name %></td>
        <td><%= station.latitude %></td>
        <td><%= station.longitude %></td>
        <td><%= station.citybik_station_uid %></td>
        <td><%= station.citybik_station_id %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

BikeSharing/app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

BikeSharing/app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @station.company %>
</p>

<p>
  <strong>Free bikes:</strong>
  <%= @station.free_bikes %>
</p>

<p>
  <strong>Empty Slots:</strong>
  <%= @station.empty_slots %>
</p>

<p>
  <strong>Slots:</strong>
  <%= @station.slots %>
</p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<p>
  <strong>Citybik_Station_UID:</strong>
  <%= @station.citybik_station_uid %>
</p>

<p>
  <strong>Citybik_Station_ID:</strong>
  <%= @station.citybik_station_id %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>